name: Cleanup Abandoned Payments

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cleanup abandoned payments
        run: |
          curl -X POST '${{ secrets.SUPABASE_FUNCTION_URL }}/cleanup-payments' \
          -H 'Authorization: Bearer ${{ secrets.FUNCTION_SECRET }}' \
          -H 'Content-Type: application/json'
        env:
          SUPABASE_FUNCTION_URL: ${{ secrets.SUPABASE_FUNCTION_URL }}
          FUNCTION_SECRET: ${{ secrets.FUNCTION_SECRET }}